language: objective-c

# Need to clone the dependent project under royratcliffe, or wherever Travis
# puts the main repo clone.
install: git clone git://github.com/royratcliffe/ActiveSupportKit.git ../ActiveSupportKit
